package modelo;
// Generated 25/09/2017 10:56:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private Integer iddepartamento;
     private String nombre;
     private Set municipios = new HashSet(0);

    public Departamento() {
    }

	
    public Departamento(String nombre) {
        this.nombre = nombre;
    }
    public Departamento(String nombre, Set municipios) {
       this.nombre = nombre;
       this.municipios = municipios;
    }
   
    public Integer getIddepartamento() {
        return this.iddepartamento;
    }
    
    public void setIddepartamento(Integer iddepartamento) {
        this.iddepartamento = iddepartamento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getMunicipios() {
        return this.municipios;
    }
    
    public void setMunicipios(Set municipios) {
        this.municipios = municipios;
    }




}


