package modelo;
// Generated 25/09/2017 10:56:56 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Detalle generated by hbm2java
 */
public class Detalle  implements java.io.Serializable {


     private Integer iddetalle;
     private Factura factura;
     private Producto producto;
     private int cantidad;
     private BigDecimal descuento;

    public Detalle() {
    }

    public Detalle(Factura factura, Producto producto, int cantidad, BigDecimal descuento) {
       this.factura = factura;
       this.producto = producto;
       this.cantidad = cantidad;
       this.descuento = descuento;
    }
   
    public Integer getIddetalle() {
        return this.iddetalle;
    }
    
    public void setIddetalle(Integer iddetalle) {
        this.iddetalle = iddetalle;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(BigDecimal descuento) {
        this.descuento = descuento;
    }




}


