package modelo;
// Generated 25/09/2017 10:56:56 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private Integer nofactura;
     private Sucursal sucursal;
     private Usuario usuario;
     private Date fecha;
     private BigDecimal total;
     private Integer estado;
     private Set modopados = new HashSet(0);
     private Set detalles = new HashSet(0);

    public Factura() {
    }

	
    public Factura(Sucursal sucursal, Usuario usuario, Date fecha, BigDecimal total) {
        this.sucursal = sucursal;
        this.usuario = usuario;
        this.fecha = fecha;
        this.total = total;
    }
    public Factura(Sucursal sucursal, Usuario usuario, Date fecha, BigDecimal total, Integer estado, Set modopados, Set detalles) {
       this.sucursal = sucursal;
       this.usuario = usuario;
       this.fecha = fecha;
       this.total = total;
       this.estado = estado;
       this.modopados = modopados;
       this.detalles = detalles;
    }
   
    public Integer getNofactura() {
        return this.nofactura;
    }
    
    public void setNofactura(Integer nofactura) {
        this.nofactura = nofactura;
    }
    public Sucursal getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(Sucursal sucursal) {
        this.sucursal = sucursal;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public Set getModopados() {
        return this.modopados;
    }
    
    public void setModopados(Set modopados) {
        this.modopados = modopados;
    }
    public Set getDetalles() {
        return this.detalles;
    }
    
    public void setDetalles(Set detalles) {
        this.detalles = detalles;
    }




}


