package modelo;
// Generated 25/09/2017 10:56:56 PM by Hibernate Tools 4.3.1



/**
 * Modopado generated by hbm2java
 */
public class Modopado  implements java.io.Serializable {


     private Integer idmodopado;
     private Factura factura;
     private String tipodePago;
     private String tipoenvio;

    public Modopado() {
    }

    public Modopado(Factura factura, String tipodePago, String tipoenvio) {
       this.factura = factura;
       this.tipodePago = tipodePago;
       this.tipoenvio = tipoenvio;
    }
   
    public Integer getIdmodopado() {
        return this.idmodopado;
    }
    
    public void setIdmodopado(Integer idmodopado) {
        this.idmodopado = idmodopado;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public String getTipodePago() {
        return this.tipodePago;
    }
    
    public void setTipodePago(String tipodePago) {
        this.tipodePago = tipodePago;
    }
    public String getTipoenvio() {
        return this.tipoenvio;
    }
    
    public void setTipoenvio(String tipoenvio) {
        this.tipoenvio = tipoenvio;
    }




}


