package modelo;
// Generated 25/09/2017 10:56:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Municipio generated by hbm2java
 */
public class Municipio  implements java.io.Serializable {


     private int idmunicipio;
     private Departamento departamento;
     private String nombre;
     private Set sucursals = new HashSet(0);

    public Municipio() {
    }

	
    public Municipio(int idmunicipio, Departamento departamento, String nombre) {
        this.idmunicipio = idmunicipio;
        this.departamento = departamento;
        this.nombre = nombre;
    }
    public Municipio(int idmunicipio, Departamento departamento, String nombre, Set sucursals) {
       this.idmunicipio = idmunicipio;
       this.departamento = departamento;
       this.nombre = nombre;
       this.sucursals = sucursals;
    }
   
    public int getIdmunicipio() {
        return this.idmunicipio;
    }
    
    public void setIdmunicipio(int idmunicipio) {
        this.idmunicipio = idmunicipio;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getSucursals() {
        return this.sucursals;
    }
    
    public void setSucursals(Set sucursals) {
        this.sucursals = sucursals;
    }




}


