package modelo;
// Generated 25/09/2017 10:56:56 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer idservicio;
     private String nombreSer;
     private String imagen;
     private BigDecimal precio;
     private String tipo;
     private Set detalles = new HashSet(0);

    public Producto() {
    }

	
    public Producto(String nombreSer, String imagen, BigDecimal precio) {
        this.nombreSer = nombreSer;
        this.imagen = imagen;
        this.precio = precio;
    }
    public Producto(String nombreSer, String imagen, BigDecimal precio, String tipo, Set detalles) {
       this.nombreSer = nombreSer;
       this.imagen = imagen;
       this.precio = precio;
       this.tipo = tipo;
       this.detalles = detalles;
    }
   
    public Integer getIdservicio() {
        return this.idservicio;
    }
    
    public void setIdservicio(Integer idservicio) {
        this.idservicio = idservicio;
    }
    public String getNombreSer() {
        return this.nombreSer;
    }
    
    public void setNombreSer(String nombreSer) {
        this.nombreSer = nombreSer;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getDetalles() {
        return this.detalles;
    }
    
    public void setDetalles(Set detalles) {
        this.detalles = detalles;
    }




}


