package modelo;
// Generated 25/09/2017 10:56:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private Integer idroles;
     private String perfil;
     private Set usuarios = new HashSet(0);

    public Roles() {
    }

    public Roles(String perfil, Set usuarios) {
       this.perfil = perfil;
       this.usuarios = usuarios;
    }
   
    public Integer getIdroles() {
        return this.idroles;
    }
    
    public void setIdroles(Integer idroles) {
        this.idroles = idroles;
    }
    public String getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(String perfil) {
        this.perfil = perfil;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


