package modelo;
// Generated 25/09/2017 10:56:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sucursal generated by hbm2java
 */
public class Sucursal  implements java.io.Serializable {


     private int idsucursal;
     private Municipio municipio;
     private Usuario usuario;
     private String nombre;
     private Set tiposericios = new HashSet(0);
     private Set facturas = new HashSet(0);

    public Sucursal() {
    }

	
    public Sucursal(int idsucursal, Municipio municipio, Usuario usuario, String nombre) {
        this.idsucursal = idsucursal;
        this.municipio = municipio;
        this.usuario = usuario;
        this.nombre = nombre;
    }
    public Sucursal(int idsucursal, Municipio municipio, Usuario usuario, String nombre, Set tiposericios, Set facturas) {
       this.idsucursal = idsucursal;
       this.municipio = municipio;
       this.usuario = usuario;
       this.nombre = nombre;
       this.tiposericios = tiposericios;
       this.facturas = facturas;
    }
   
    public int getIdsucursal() {
        return this.idsucursal;
    }
    
    public void setIdsucursal(int idsucursal) {
        this.idsucursal = idsucursal;
    }
    public Municipio getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(Municipio municipio) {
        this.municipio = municipio;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getTiposericios() {
        return this.tiposericios;
    }
    
    public void setTiposericios(Set tiposericios) {
        this.tiposericios = tiposericios;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }




}


