package modelo;
// Generated 25/09/2017 10:56:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Suscripcion generated by hbm2java
 */
public class Suscripcion  implements java.io.Serializable {


     private Integer idSuscripcion;
     private String nombre;
     private String tarifa;
     private String descripcionSer;
     private Set usuarios = new HashSet(0);

    public Suscripcion() {
    }

	
    public Suscripcion(String nombre, String tarifa, String descripcionSer) {
        this.nombre = nombre;
        this.tarifa = tarifa;
        this.descripcionSer = descripcionSer;
    }
    public Suscripcion(String nombre, String tarifa, String descripcionSer, Set usuarios) {
       this.nombre = nombre;
       this.tarifa = tarifa;
       this.descripcionSer = descripcionSer;
       this.usuarios = usuarios;
    }
   
    public Integer getIdSuscripcion() {
        return this.idSuscripcion;
    }
    
    public void setIdSuscripcion(Integer idSuscripcion) {
        this.idSuscripcion = idSuscripcion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTarifa() {
        return this.tarifa;
    }
    
    public void setTarifa(String tarifa) {
        this.tarifa = tarifa;
    }
    public String getDescripcionSer() {
        return this.descripcionSer;
    }
    
    public void setDescripcionSer(String descripcionSer) {
        this.descripcionSer = descripcionSer;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


